# Generated by Django 5.0.7 on 2024-08-02 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='recipes/images/modulos')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AcessoModulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.modulos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=255)),
                ('icon', models.ImageField(null=True, upload_to='recipes/images/usuarios')),
                ('modulos', models.ManyToManyField(related_name='usuarios', through='almoxarifado.AcessoModulos', to='almoxarifado.modulos')),
            ],
        ),
        migrations.AddField(
            model_name='acessomodulos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='acessomodulos',
            unique_together={('usuario', 'modulo')},
        ),
    ]
