# Generated by Django 5.0.7 on 2024-09-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0004_log_pedido_log_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='log',
            name='usuario',
        ),
    ]
