# Generated by Django 5.0.7 on 2024-09-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_remove_log_pedido_remove_log_usuario'),
        ('cliente', '0002_remove_pedido_usuario_delete_itenspedido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
