# Generated by Django 5.1.1 on 2024-09-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
