# Generated by Django 5.0.7 on 2024-09-11 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0003_log_produto'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.pedido'),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almoxarifado.usuario'),
        ),
    ]
