# Generated by Django 5.1.1 on 2024-09-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_remove_pedido_hora_alter_itenspedido_pedido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
