# Generated by Django 5.0.7 on 2024-09-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0008_log_pedido_log_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
    ]
