# Generated by Django 5.0.7 on 2024-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0009_remove_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='medida',
            field=models.CharField(choices=[('Caixa', 'Caixa'), ('Unidade', 'Unidade')], default='Unidade', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='minimo',
            field=models.IntegerField(default=0),
        ),
    ]
