# Generated by Django 5.0.7 on 2024-09-11 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almoxarifado', '0005_remove_log_pedido_remove_log_usuario'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ItensPedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
